<a href="https://colab.research.google.com/github/harkie24/genlink/blob/main/notebooks/Gene_Biotype_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
genes = pd.read_csv("/content/ensembl_genes.csv")
diseases = pd.read_csv("/content/rare_gene_disease_dataset.csv")

In [5]:
merged = pd.merge(diseases, genes, left_on = 'gene_symbol', right_on = 'gene_symbol', how = 'inner')
merged.head()

,disease,gene_symbol,gene_full_name,ensembl_gene_id,chromosome,start,end,strand,biotype,description
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7,ENSG00000166813,15,89608789,89663098,-1,protein_coding,kinesin family member 7 [Source:HGNC Symbol;Ac...
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin,ENSG00000153015,5,64766368,65102412,1,protein_coding,CWC27 spliceosome associated cyclophilin [Sour...
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase,ENSG00000038002,4,177430774,177442444,-1,protein_coding,aspartylglucosaminidase [Source:HGNC Symbol;Ac...
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1,ENSG00000144455,3,3700814,4467273,-1,protein_coding,sulfatase modifying factor 1 [Source:HGNC Symb...
4,Beta-mannosidosis,MANBA,mannosidase beta,ENSG00000109323,4,102630770,102760999,-1,protein_coding,mannosidase beta [Source:HGNC Symbol;Acc:HGNC:...

**Top 5 Biotypes**

In [6]:
top5_biotype = (merged['biotype'].value_counts())
top5_biotype

biotype
protein_coding            8229
Mt_tRNA                     36
lncRNA                      28
snRNA                        7
IG_C_gene                    5
miRNA                        4
ribozyme                     3
IG_V_gene                    2
Mt_rRNA                      2
TEC                          2
unprocessed_pseudogene       1
TR_C_gene                    1
snoRNA                       1
Name: count, dtype: int64

**Calculating percentages**

In [7]:
biotype_df = (merged['biotype'].value_counts().reset_index())
biotype_df

                   biotype  count
0           protein_coding   8229
1                  Mt_tRNA     36
2                   lncRNA     28
3                    snRNA      7
4                IG_C_gene      5
5                    miRNA      4
6                 ribozyme      3
7                IG_V_gene      2
8                  Mt_rRNA      2
9                      TEC      2
10  unprocessed_pseudogene      1
11               TR_C_gene      1
12                  snoRNA      1

In [8]:
biotype_df['Percentage'] = (biotype_df['count']/biotype_df['count'].sum())*100
biotype_df

                   biotype  count  Percentage
0           protein_coding   8229   98.894364
1                  Mt_tRNA     36    0.432640
2                   lncRNA     28    0.336498
3                    snRNA      7    0.084125
4                IG_C_gene      5    0.060089
5                    miRNA      4    0.048071
6                 ribozyme      3    0.036053
7                IG_V_gene      2    0.024036
8                  Mt_rRNA      2    0.024036
9                      TEC      2    0.024036
10  unprocessed_pseudogene      1    0.012018
11               TR_C_gene      1    0.012018
12                  snoRNA      1    0.012018

**Finding the Most Common Biotype**

idxmax() returns the index of the maximum

In [9]:
most_common = (merged['biotype'].value_counts().idxmax())
print("Most common biotype:", most_common)

Most common biotype: protein_coding

**Finding the Least Common Biotype**

In [10]:
least_common = (merged['biotype'].value_counts().idxmin())
print("Least common biotype:", least_common)

Least common biotype: unprocessed_pseudogene

**Filter only Protein-Coding Genes**

In [11]:
protein_genes = merged[ merged['biotype'] == 'protein_coding']
protein_genes.head()

,disease,gene_symbol,gene_full_name,ensembl_gene_id,chromosome,start,end,strand,biotype,description
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7,ENSG00000166813,15,89608789,89663098,-1,protein_coding,kinesin family member 7 [Source:HGNC Symbol;Ac...
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin,ENSG00000153015,5,64766368,65102412,1,protein_coding,CWC27 spliceosome associated cyclophilin [Sour...
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase,ENSG00000038002,4,177430774,177442444,-1,protein_coding,aspartylglucosaminidase [Source:HGNC Symbol;Ac...
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1,ENSG00000144455,3,3700814,4467273,-1,protein_coding,sulfatase modifying factor 1 [Source:HGNC Symb...
4,Beta-mannosidosis,MANBA,mannosidase beta,ENSG00000109323,4,102630770,102760999,-1,protein_coding,mannosidase beta [Source:HGNC Symbol;Acc:HGNC:...

**Number of Diseases per Biotype**

In [12]:
disease_per_biotype = (merged.groupby('biotype')['disease'].nunique().sort_values(ascending=False))
disease_per_biotype

biotype
protein_coding            4078
lncRNA                      25
Mt_tRNA                     15
snRNA                        7
IG_C_gene                    4
miRNA                        4
ribozyme                     3
IG_V_gene                    2
Mt_rRNA                      2
TEC                          2
TR_C_gene                    1
snoRNA                       1
unprocessed_pseudogene       1
Name: disease, dtype: int64

**Complete Analysis**

.agg() allows multiple different calculations on different columns at the same time

In [13]:
biotype_analysis = (merged.groupby('biotype').agg(
    Total_Genes = ('gene_symbol', 'nunique'),
    Total_Diseases = ('disease', 'nunique'),
).sort_values(
    by = 'Total_Genes',
    ascending = False
)
)
biotype_analysis

                        Total_Genes  Total_Diseases
biotype
protein_coding                 4457            4078
Mt_tRNA                          15              15
lncRNA                           13              25
IG_C_gene                         4               4
miRNA                             4               4
snRNA                             4               7
IG_V_gene                         2               2
TEC                               2               2
Mt_rRNA                           1               2
TR_C_gene                         1               1
ribozyme                          1               3
snoRNA                            1               1
unprocessed_pseudogene            1               1